### ISSUE TITLE
readOnly configuration also takes a String

### ISSUE THREAD

**Issue by kiritsuku** [antonkulaga/codemirror-facade#3]
The documentation for the `readOnly` config option:

```
readOnly: boolean|string
    This disables editing of the editor content by the user. If the special value "nocursor" is given (instead of simply true), focusing of the editor is also disallowed.
```

However, in the facade, there exists only a function that takes a `Boolean` but none that takes also a string.

**Comment by antonkulaga** [comment]
I use codemirror facade sometimes but not often that is why some methods in facade can be not complete or can change (with newer versions of Codemirror). Right now I am busy working on other libs, so feel free to make PRs if something is missing/wrong - I will merge.

**Comment by antonkulaga** [comment]
I added String support in the latest commit
