### ISSUE TITLE
Release without three

### ISSUE THREAD

**Issue by danielwegener** [antonkulaga/codemirror-facade#4]
It would be great if you could release this facade without the three.js packages. Currently three.js facade depends on this facade which kind of puts three.js facade classes twice on the classpath for the preview module (once the local facade module and the packages bundled with this module). If you'd now try to restructure the three facade, the preview won't compile because it finds ambigious classes.

**Comment by antonkulaga** [comment]
I do not think it depends on threejs anywhere
